name: Feature Request
description: Suggest a new feature or improvement
labels: ['enhancement']
body:
    - type: markdown
      attributes:
          value: |
              Thanks for suggesting a feature! We'd love to hear your ideas.

    - type: textarea
      id: description
      attributes:
          label: Feature Description
          description: A clear description of the feature you'd like
          placeholder: What would you like Moonvert to do?
      validations:
          required: true

    - type: textarea
      id: problem
      attributes:
          label: Problem it Solves
          description: What problem does this feature solve? What's your use case?
          placeholder: I'm trying to... but currently...
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives Considered
          description: Have you considered any alternative solutions or workarounds?

    - type: dropdown
      id: category
      attributes:
          label: Category
          options:
              - New file format support
              - Conversion options
              - User interface
              - Performance
              - Integration (other apps/services)
              - Other
      validations:
          required: true

    - type: textarea
      id: additional
      attributes:
          label: Additional Context
          description: Any mockups, screenshots, or examples that might help illustrate your idea
